let nav = {
    menu:[
        {id:"m0",name:"一级菜单",depth:1,link:"#",menu:[
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单四级菜单四级菜单四级菜单四级菜单四级菜单四级菜单四级菜单四级菜单四级菜单四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]}
        ]},
        {id:"m0",name:"一级菜单",depth:1,link:"#",menu:[
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]}
        ]},
        {id:"m0",name:"一级菜单",depth:1,link:"#",menu:[
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]}
        ]},
        {id:"m0",name:"一级菜单",depth:1,link:"#",menu:[
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]}
        ]},
        {id:"m0",name:"一级菜单",depth:1,link:"#",menu:[
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]}
        ]},
        {id:"m0",name:"一级菜单",depth:1,link:"#",menu:[
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]},
            {id:"m0",name:"二级菜单",depth:2,link:"#",menu:[
                {id:"m0",name:"三级菜单",depth:3,link:"#"},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]},
                {id:"m0",name:"三级菜单",depth:3,link:"#",menu:[
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                    {id:"m0",name:"四级菜单",depth:4,link:"#"},
                ]}
            ]}
        ]}
    ]
}
export default nav;